name: Falloutcraft
main: io.github.kuohsuanlo.falloutcraft.FalloutcraftPlugin
version: 1.0.3
softdepend: [PlaceholderAPI]
commands:
    fostatus:
        description: check falloutcraft status.
        usage: /fostatus
        aliases: [fos]
    foupdate:
        description: see the spigot page
        usage: /foupdate
    fosetf:
        description: see the spigot page
        usage: /fosetf playerid value <add>
    fosetd:
        description: see the spigot page
        usage: /fosetd playerid value <add>
    fosetr:
        description: see the spigot page
        usage: /fosetr playerid value <add>
permissions:
    falloutcraft.*:
        description: Gives access to all fallout commands
        children:
            falloutcraft.fostatus: true
            falloutcraft.foupdate: true
            falloutcraft.setradiation: true
            falloutcraft.setdehydration: true
            falloutcraft.setfatigue: true
            falloutcraft.addradiation: true
            falloutcraft.adddehydration: true
            falloutcraft.addfatigue: true
    falloutcraft.fostatus:
        description: check falloutcraft status.
        default: true
    falloutcraft.setradiation:
        description: set a player's radiation level
        default: op
    falloutcraft.setdehydration:
        description: set a player's dehydration level
        default: op
    falloutcraft.setfatigue:
        description: set a player's fatigue level
        default: op