name: Falloutcraft
main: io.github.kuohsuanlo.falloutcraft.FalloutcraftPlugin
version: 1.0.2f
softdepend: [PlaceholderAPI]
commands:
  fostatus:
    description: check falloutcraft status.
    usage: "/fostatus"
    aliases: [fos]
  foupdate:
    description: update falloutcraft status effect.
    usage: "/foupdate"
  fosetf:
    description: set the player's fatigue value.
    usage: "/fosetf playerid value"
  fosetd:
    description: set the player's dehydration value.
    usage: "/fosetd playerid value"
  fosetr:
    description: set the player's radiation value.
    usage: "/fosetr playerid value"
  fobook:
    description: give a book to the player.
    usage: "/fobook"
    aliases: [fob]

permissions:
    falloutcraft.*:
        description: Gives access to all fallout commands
        children:
            falloutcraft.fostatus: true
            falloutcraft.foupdate: true
            falloutcraft.setradiation: true
            falloutcraft.setdehydration: true
            falloutcraft.setfatigue: true
    falloutcraft.fostatus:
        description: check falloutcraft status.
        default: true
    falloutcraft.setradiation:
        description: set a player's radiation level
        default: op
    falloutcraft.setdehydration:
        description: set a player's dehydration level
        default: op
    falloutcraft.setfatigue:
        description: set a player's fatigue level
        default: op