name: Falloutcraftr
main: io.github.kuohsuanlo.falloutcraft.FalloutcraftPlugin
version: ${version}
commands:
  pos:
    description: reload falloutcraft.
    usage: "reload falloutcraft"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug